from src.business_logic.common.exceptions.base import UnexpectedError


class DAOError(UnexpectedError):
    pass
